ENGINEERING_RECORDS = [
    {
        "slug": "fairway-frame-pipeline",
        "title": "A camera pipeline that skips work instead of queuing it",
        "preview": "Fairway processes live body movement while the golfer continues practising. Slow inference must not build a backlog of old frames.",
        "kind": "Owned product · Experimental",
        "need": "A golfer needs the overlay to follow current movement while the camera keeps presenting video. Pose inference can take longer than the interval between camera frames.",
        "role": "I developed Fairway through Vriksh, including the browser camera pipeline, pose processing and saved skeleton replay.",
        "decision": "I allow one frame acquisition or inference job in flight. When the pipeline is busy, a fresh camera frame is skipped. A worker runs pose inference where the browser supports it; a main-thread fallback handles other supported browsers.",
        "tradeoff": "Skipping frames limits queued work, but loses temporal samples during fast movement. The detector must withhold event timing when those gaps make an estimate unreliable. The fallback can also compete with UI work.",
        "artifact_title": "Frame admission in the implemented pipeline",
        "artifact": "if (this.busy || now - this.lastSent < this.interval) {\n  this.stats.skipped++;\n  return;\n}\nthis.busy = true;\nthis.lastSent = now;",
        "sequence": [
            "Camera presents a fresh frame",
            "Busy? Skip inference for this frame",
            "Transfer one image to pose processing",
            "Receive timestamped landmarks and release the busy gate",
        ],
        "outcome": "The pipeline bounds acquisition and inference to one job at a time. The saved movement replay shows landmarks produced from a test clip. It demonstrates the replay path; golf timing accuracy still needs broader labelled real-swing validation.",
        "limit": "Face-on full-body framing; projected 2D observations. The replay uses a slow-motion test clip with timing disabled.",
        "image": "fairway",
        "caption": "Saved skeleton replay from a test clip. Timing disabled.",
        "link": "/projects#project-golf-swing-analyzer",
        "link_label": "Open Fairway details",
    },
    {
        "slug": "callrenard-call-states",
        "title": "Ending an unclear intake call with a follow-up record",
        "preview": "CallRenard uses explicit consent and question states to collect configured keypad responses.",
        "kind": "Owned product · In development",
        "need": "A configured intake workflow needs a defined outcome when a caller chooses an unsupported department or repeatedly gives an invalid answer.",
        "role": "I develop CallRenard through Vriksh. This record covers the implemented call-state and summary behaviour.",
        "decision": "The implementation separates consent, intent, details and confirmation. An unrecognized intent escalates immediately; invalid detail answers have a retry limit. Escalation speaks a closing message, hangs up and invokes the configured summary-delivery integration.",
        "tradeoff": "Configured keypad choices constrain what the caller can express, but make input validation and state changes explicit. Escalation creates a follow-up path; the implementation does not perform a live transfer.",
        "artifact_title": "Summary formatter output · sample answers",
        "artifact": "CallRenard summary for realtor call.\nintent: buyer\nbudget: 500k-1m\ntimeline: 1-3mo",
        "sequence": [
            "Disclose automation and request consent",
            "Collect configured keypad responses",
            "Confirm answers or escalate",
            "End call and request summary delivery",
        ],
        "outcome": "The backend defines separate completion and escalation outcomes. The displayed artifact is output from its formatter, using demonstration answers. Public access is by arranged demonstration.",
        "limit": "The artifact shows formatting. Telephone handling and message delivery require a live demonstration; general speech transcription and live transfer are outside this demonstrated scope.",
        "image": "",
        "caption": "",
        "link": "https://vriksh.ca/ventures/callrenard",
        "link_label": "Arrange a demonstration through Vriksh",
    },
]
